services:
  database_container:
    container_name: database
    image: postgres:16.3-alpine3.20
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  application_container:
    container_name: application
    build: .
    env_file:
      - .env
    depends_on:
      - database_container
    command: sh -c 'sleep 5 && alembic upgrade head && uvicorn src.main:app --host ${APP_HOST} --port ${APP_PORT}'
    ports:
      - ${APP_PORT}:${APP_PORT}
